spring:
  application:
    name: teknisio-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/teknisio_db
    username: teknisio_user
    password: teknisio_pass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

server:
  port: 8080
