spring:
  application:
    name: teknisio-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/teknisio_db
    username: teknisio_user
    password: teknisio_pass

  jpa:
    hibernate:
      # Hibernate otomatis buat tabel dari model Java
      # Uncomment/Comment this
      # ddl-auto: update

      # Hibernate manual buat tabel
      # Uncomment/Comment this
      ddl-auto: validate
    show-sql: true

  security:
    user:
      name: admin
      password: admin

server:
  port: 8080
