services:
  postgres:
    image: postgres:16
    container_name: teknisio_db
    environment:
      POSTGRES_DB: teknisio_db
      POSTGRES_USER: teknisio_user
      POSTGRES_PASSWORD: teknisio_pass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
