-- Active: 1779499726179@@127.0.0.1@5432@teknisio_db

-- ============================================================
-- ENUMS
-- ============================================================

CREATE TYPE USER_ROLE AS ENUM (
  'CUSTOMER', 'TEKNISI', 'ADMIN'
);

CREATE TYPE USER_STATUS AS ENUM (
  'ACTIVE', 'INACTIVE', 'BANNED', 'SUSPENDED'
);

CREATE TYPE TEKNISI_STATUS AS ENUM (
  'ONLINE', 'OFFLINE', 'BUSY', 'ON_LEAVE'
);

CREATE TYPE TEKNISI_SPESIALISASI AS ENUM (
  'AC', 'FRIDGE', 'WASHING_MACHINE', 'RICE_COOKER', 'OVEN', 'TELEVISION', 'FAN', 'MIXER'
);

CREATE TYPE REQUEST_STATUS AS ENUM (
  'WAITING', 'ACCEPTED', 'ON_PROGRESS', 'COMPLETED', 'CANCELLED', 'REJECTED'
);

CREATE TYPE PESAN_TYPE AS ENUM (
  'TEXT', 'IMAGE', 'SYSTEM'
);

CREATE TYPE NOTIFICATION_REFERENCE_TYPE AS ENUM (
  'PERMINTAAN', 'CHAT', 'REVIEW'
);

CREATE TYPE HARI_ENUM AS ENUM (
  'SENIN', 'SELASA', 'RABU', 'KAMIS', 'JUMAT', 'SABTU', 'MINGGU'
);
